/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.minesweeper.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.codegen.minesweeper.Keys;
import org.jooq.codegen.minesweeper.Minesweeper;
import org.jooq.codegen.minesweeper.tables.records.GameRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game extends TableImpl<GameRecord> {

    private static final long serialVersionUID = 261573351;

    /**
     * The reference instance of <code>minesweeper.game</code>
     */
    public static final Game GAME = new Game();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameRecord> getRecordType() {
        return GameRecord.class;
    }

    /**
     * The column <code>minesweeper.game.id</code>.
     */
    public final TableField<GameRecord, UShort> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>minesweeper.game.status</code>.
     */
    public final TableField<GameRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>minesweeper.game.columns</code>.
     */
    public final TableField<GameRecord, Integer> COLUMNS = createField(DSL.name("columns"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>minesweeper.game.rows</code>.
     */
    public final TableField<GameRecord, Integer> ROWS = createField(DSL.name("rows"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>minesweeper.game.mines</code>.
     */
    public final TableField<GameRecord, Integer> MINES = createField(DSL.name("mines"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>minesweeper.game.user_id</code>.
     */
    public final TableField<GameRecord, Integer> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>minesweeper.game.duration</code>.
     */
    public final TableField<GameRecord, Integer> DURATION = createField(DSL.name("duration"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>minesweeper.game.user_account_id</code>.
     */
    public final TableField<GameRecord, UShort> USER_ACCOUNT_ID = createField(DSL.name("user_account_id"), org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>minesweeper.game</code> table reference
     */
    public Game() {
        this(DSL.name("game"), null);
    }

    /**
     * Create an aliased <code>minesweeper.game</code> table reference
     */
    public Game(String alias) {
        this(DSL.name(alias), GAME);
    }

    /**
     * Create an aliased <code>minesweeper.game</code> table reference
     */
    public Game(Name alias) {
        this(alias, GAME);
    }

    private Game(Name alias, Table<GameRecord> aliased) {
        this(alias, aliased, null);
    }

    private Game(Name alias, Table<GameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Game(Table<O> child, ForeignKey<O, GameRecord> key) {
        super(child, key, GAME);
    }

    @Override
    public Schema getSchema() {
        return Minesweeper.MINESWEEPER;
    }

    @Override
    public Identity<GameRecord, UShort> getIdentity() {
        return Keys.IDENTITY_GAME;
    }

    @Override
    public UniqueKey<GameRecord> getPrimaryKey() {
        return Keys.KEY_GAME_PRIMARY;
    }

    @Override
    public List<UniqueKey<GameRecord>> getKeys() {
        return Arrays.<UniqueKey<GameRecord>>asList(Keys.KEY_GAME_PRIMARY);
    }

    @Override
    public List<ForeignKey<GameRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GameRecord, ?>>asList(Keys.FK_USER_ACCOUNT_ID);
    }

    public UserAccount userAccount() {
        return new UserAccount(this, Keys.FK_USER_ACCOUNT_ID);
    }

    @Override
    public Game as(String alias) {
        return new Game(DSL.name(alias), this);
    }

    @Override
    public Game as(Name alias) {
        return new Game(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(String name) {
        return new Game(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(Name name) {
        return new Game(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<UShort, String, Integer, Integer, Integer, Integer, Integer, UShort> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
