/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.minesweeper.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.codegen.minesweeper.tables.Game;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record8<UShort, String, Integer, Integer, Integer, Integer, Integer, UShort> {

    private static final long serialVersionUID = -943069665;

    /**
     * Setter for <code>minesweeper.game.id</code>.
     */
    public void setId(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>minesweeper.game.id</code>.
     */
    public UShort getId() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>minesweeper.game.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>minesweeper.game.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>minesweeper.game.columns_number</code>.
     */
    public void setColumnsNumber(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>minesweeper.game.columns_number</code>.
     */
    public Integer getColumnsNumber() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>minesweeper.game.rows_number</code>.
     */
    public void setRowsNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>minesweeper.game.rows_number</code>.
     */
    public Integer getRowsNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>minesweeper.game.mines</code>.
     */
    public void setMines(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>minesweeper.game.mines</code>.
     */
    public Integer getMines() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>minesweeper.game.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>minesweeper.game.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>minesweeper.game.duration</code>.
     */
    public void setDuration(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>minesweeper.game.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>minesweeper.game.user_account_id</code>.
     */
    public void setUserAccountId(UShort value) {
        set(7, value);
    }

    /**
     * Getter for <code>minesweeper.game.user_account_id</code>.
     */
    public UShort getUserAccountId() {
        return (UShort) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UShort> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UShort, String, Integer, Integer, Integer, Integer, Integer, UShort> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UShort, String, Integer, Integer, Integer, Integer, Integer, UShort> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UShort> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<String> field2() {
        return Game.GAME.STATUS;
    }

    @Override
    public Field<Integer> field3() {
        return Game.GAME.COLUMNS_NUMBER;
    }

    @Override
    public Field<Integer> field4() {
        return Game.GAME.ROWS_NUMBER;
    }

    @Override
    public Field<Integer> field5() {
        return Game.GAME.MINES;
    }

    @Override
    public Field<Integer> field6() {
        return Game.GAME.USER_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Game.GAME.DURATION;
    }

    @Override
    public Field<UShort> field8() {
        return Game.GAME.USER_ACCOUNT_ID;
    }

    @Override
    public UShort component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStatus();
    }

    @Override
    public Integer component3() {
        return getColumnsNumber();
    }

    @Override
    public Integer component4() {
        return getRowsNumber();
    }

    @Override
    public Integer component5() {
        return getMines();
    }

    @Override
    public Integer component6() {
        return getUserId();
    }

    @Override
    public Integer component7() {
        return getDuration();
    }

    @Override
    public UShort component8() {
        return getUserAccountId();
    }

    @Override
    public UShort value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStatus();
    }

    @Override
    public Integer value3() {
        return getColumnsNumber();
    }

    @Override
    public Integer value4() {
        return getRowsNumber();
    }

    @Override
    public Integer value5() {
        return getMines();
    }

    @Override
    public Integer value6() {
        return getUserId();
    }

    @Override
    public Integer value7() {
        return getDuration();
    }

    @Override
    public UShort value8() {
        return getUserAccountId();
    }

    @Override
    public GameRecord value1(UShort value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public GameRecord value3(Integer value) {
        setColumnsNumber(value);
        return this;
    }

    @Override
    public GameRecord value4(Integer value) {
        setRowsNumber(value);
        return this;
    }

    @Override
    public GameRecord value5(Integer value) {
        setMines(value);
        return this;
    }

    @Override
    public GameRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public GameRecord value7(Integer value) {
        setDuration(value);
        return this;
    }

    @Override
    public GameRecord value8(UShort value) {
        setUserAccountId(value);
        return this;
    }

    @Override
    public GameRecord values(UShort value1, String value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, UShort value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(UShort id, String status, Integer columnsNumber, Integer rowsNumber, Integer mines, Integer userId, Integer duration, UShort userAccountId) {
        super(Game.GAME);

        set(0, id);
        set(1, status);
        set(2, columnsNumber);
        set(3, rowsNumber);
        set(4, mines);
        set(5, userId);
        set(6, duration);
        set(7, userAccountId);
    }
}
