/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.minesweeper.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.codegen.minesweeper.tables.UserAccount;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccountRecord extends UpdatableRecordImpl<UserAccountRecord> implements Record6<UShort, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 656038899;

    /**
     * Setter for <code>minesweeper.user_account.id</code>.
     */
    public void setId(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>minesweeper.user_account.id</code>.
     */
    public UShort getId() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>minesweeper.user_account.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>minesweeper.user_account.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>minesweeper.user_account.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>minesweeper.user_account.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>minesweeper.user_account.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>minesweeper.user_account.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>minesweeper.user_account.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>minesweeper.user_account.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>minesweeper.user_account.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>minesweeper.user_account.date_of_birth</code>.
     */
    public LocalDateTime getDateOfBirth() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UShort> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UShort, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UShort, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UShort> field1() {
        return UserAccount.USER_ACCOUNT.ID;
    }

    @Override
    public Field<String> field2() {
        return UserAccount.USER_ACCOUNT.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return UserAccount.USER_ACCOUNT.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return UserAccount.USER_ACCOUNT.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return UserAccount.USER_ACCOUNT.LAST_NAME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserAccount.USER_ACCOUNT.DATE_OF_BIRTH;
    }

    @Override
    public UShort component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public LocalDateTime component6() {
        return getDateOfBirth();
    }

    @Override
    public UShort value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public LocalDateTime value6() {
        return getDateOfBirth();
    }

    @Override
    public UserAccountRecord value1(UShort value) {
        setId(value);
        return this;
    }

    @Override
    public UserAccountRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserAccountRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserAccountRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserAccountRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserAccountRecord value6(LocalDateTime value) {
        setDateOfBirth(value);
        return this;
    }

    @Override
    public UserAccountRecord values(UShort value1, String value2, String value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccountRecord
     */
    public UserAccountRecord() {
        super(UserAccount.USER_ACCOUNT);
    }

    /**
     * Create a detached, initialised UserAccountRecord
     */
    public UserAccountRecord(UShort id, String email, String password, String firstName, String lastName, LocalDateTime dateOfBirth) {
        super(UserAccount.USER_ACCOUNT);

        set(0, id);
        set(1, email);
        set(2, password);
        set(3, firstName);
        set(4, lastName);
        set(5, dateOfBirth);
    }
}
