/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.minesweeper;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.codegen.minesweeper.tables.Game;
import org.jooq.codegen.minesweeper.tables.Square;
import org.jooq.codegen.minesweeper.tables.UserAccount;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Minesweeper extends SchemaImpl {

    private static final long serialVersionUID = 510660912;

    /**
     * The reference instance of <code>minesweeper</code>
     */
    public static final Minesweeper MINESWEEPER = new Minesweeper();

    /**
     * The table <code>minesweeper.game</code>.
     */
    public final Game GAME = Game.GAME;

    /**
     * The table <code>minesweeper.square</code>.
     */
    public final Square SQUARE = Square.SQUARE;

    /**
     * The table <code>minesweeper.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * No further instances allowed
     */
    private Minesweeper() {
        super("minesweeper", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Game.GAME,
            Square.SQUARE,
            UserAccount.USER_ACCOUNT);
    }
}
