/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.minesweeper;


import org.jooq.codegen.minesweeper.tables.Game;
import org.jooq.codegen.minesweeper.tables.Square;
import org.jooq.codegen.minesweeper.tables.UserAccount;


/**
 * Convenience access to all tables in minesweeper
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>minesweeper.game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>minesweeper.square</code>.
     */
    public static final Square SQUARE = Square.SQUARE;

    /**
     * The table <code>minesweeper.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;
}
